export const DEFAULT_ANIMATION_DELAY = 750;
export const DEFAULT_ANIMATION_DURATION = 500;
export const DEFAULT_SHORT_ANIMATION_DURATION = 350;

export const CAPTURE_TUTORIAL_DURATION = 4000;

export const FAILIURE_ANIMATION_DURATION = 1000;