export const DEFAULT_FACING_MODE = "environment";

export const REQUESTED_CAPTURE_WIDTH_IN_PX_2XL = 1920;
export const REQUESTED_CAPTURE_HEIGHT_IN_PX_2XL = 1080;

export const REQUESTED_CAPTURE_WIDTH_IN_PX_XL = 1920;
export const REQUESTED_CAPTURE_HEIGHT_IN_PX_XL = 1080;

export const REQUESTED_CAPTURE_WIDTH_IN_PX_LG = 2177;
export const REQUESTED_CAPTURE_HEIGHT_IN_PX_LG = 1634;

export const REQUESTED_CAPTURE_WIDTH_IN_PX_MD = 2177;
export const REQUESTED_CAPTURE_HEIGHT_IN_PX_MD = 1634;

export const REQUESTED_CAPTURE_WIDTH_IN_PX_SM = 1634;
export const REQUESTED_CAPTURE_HEIGHT_IN_PX_SM = 2177;