export const CLASS_NAME_DELIMITER = '-';

export const DEFAULT_IMAGES_LOADING_DELAY_TIME_IN_MS = 50;
export const DEFAULT_IMAGES_LOADING_TIMEOUT_AFTER_N_MS = 5000;

export const EMPTY_STRING = '';
export const TRUNCATE_SUFFIX = '...';

export const DEFAULT_REQUEST_TIMEOUT_IN_MS = 10000;

export const AQI_PREDICTION_HIGH_DISCREPENCY_LIMIT = 50;